openapi: 3.0.0
info:
  title: Neural Network API
  version: 1.0.0
  description: API for accessing text-based neural networks
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
servers:
  - url: http://localhost:5000/api
paths:
  /auth/register:
    post:
      summary: Register a new user
      tags:
        - Authentication
      requestBody:
        description: User credentials
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  example: user@example.com
                password:
                  type: string
                  example: password123
      responses:
        '201':
          description: User registered successfully
        '400':
          description: User already exists
        '500':
          description: Server error
  /auth/login:
    post:
      summary: Login a user
      tags:
        - Authentication
      requestBody:
        description: User credentials
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  example: user@example.com
                password:
                  type: string
                  example: password123
      responses:
        '200':
          description: User logged in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: JWT token
        '400':
          description: Invalid credentials
        '500':
          description: Server error
  /balance:
    get:
      summary: Get user balance
      tags:
        - Balance
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User balance
          content:
            application/json:
              schema:
                type: object
                properties:
                  balance:
                    type: number
        '401':
          description: Unauthorized
        '500':
          description: Server error
  /balance/update:
    post:
      summary: Update user balance
      tags:
        - Balance
      security:
        - bearerAuth: []
      requestBody:
        description: Update balance
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - userId
                - amount
              properties:
                userId:
                  type: string
                amount:
                  type: number
      responses:
        '200':
          description: Balance updated successfully
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Server error
  /generate:
    post:
      summary: Generate text using a specified model
      tags:
        - Generation
      security:
        - bearerAuth: []
      requestBody:
        description: Generation parameters
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - model
                - prompt
              properties:
                model:
                  type: string
                  example: gpt-4
                prompt:
                  type: string
                  example: "Once upon a time"
      responses:
        '200':
          description: Streaming text response
          content:
            text/event-stream:
              schema:
                type: string
                example: "data: This is a streaming response\\n\\n"
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Server error
